monitoring:
  elasticsearch:
    hosts: http://localhost:9200
    enabled: false
    step: PT1M
    index: qalipsis-metrics
    index-date-format: yyyy-MM-dd
    auto-create-index: true

events:
  export:
    elasticsearch:
      enabled: false
      min-level: INFO
      urls: http://localhost:9200
      index-prefix: qalipsis-events
      index-date-pattern: yyyy-MM-dd
      duration-as-nano: false
      linger-period: 10s
      batch-size: 2000
      publishers: 1
      username:
      password:
      shards: 1
      replicas: 0
