events:
  export:
    elasticsearch:
      enabled: false
      minLevel: INFO
      urls: http://localhost:9200
      indexPrefix: qalipsis-events
      indexDatePattern: yyyy-MM-dd
      durationAsNano: false
      lingerPeriod: 10s
      batchSize: 2000
      publishers: 1
      username:
      password:
      shards: 1
      replicas: 0

# Disables the native micronaut registry.
micronaut.metrics.export.elastic.enabled: false

meters:
  elasticsearch:
    hosts: http://localhost:9200
    host: ${meters.elasticsearch.hosts}
    enabled: false
    step: PT10S
    index: qalipsis-meters
    indexDateFormat: yyyy-MM-dd
    autoCreateIndex: true
